"""Utilities for handling generator config with nested structure.

This module provides utilities for working with the nested generator_config
structure.

Nested structure (REQUIRED):
    {
        "pipeline": {"n_parameter_sets": 100, "n_subruns": 10, ...},
        "estimator": {"type": "kde", "bandwidth": 0.1, ...},
        "training": {"mixture_probabilities": [0.8, 0.1, 0.1], ...},
        "simulator": {"delta_t": 0.001, "max_t": 20.0, ...},
        "output": {"folder": "...", "pickle_protocol": 4, ...},
    }

Note: Only nested configs are supported. Flat configs are no longer accepted.
"""

from typing import Any


def get_nested_config(config: dict, section: str, key: str, default: Any = None) -> Any:
    """Get a value from nested config structure.

    Args:
        config: Generator configuration dictionary (must use nested structure)
        section: Nested section name ("pipeline", "estimator", "training", "simulator", "output")
        key: Key name within the section
        default: Default value if key not found

    Returns:
        Value from nested structure if available, else default

    Examples:
        >>> config = {"pipeline": {"n_parameter_sets": 100}}
        >>> get_nested_config(config, "pipeline", "n_parameter_sets")
        100

        >>> get_nested_config(config, "pipeline", "missing_key", default=42)
        42
    """
    # Get value from nested structure
    if section in config and isinstance(config[section], dict):
        if key in config[section]:
            return config[section][key]

    # Return default if not found
    return default


def has_nested_structure(config: dict) -> bool:
    """Check if config uses the required nested structure.

    Args:
        config: Generator configuration dictionary

    Returns:
        True if config has nested sections (required format), False otherwise

    Note:
        Only nested configs are supported. This function validates that configs
        have the correct structure with at least one of the required sections.
    """
    nested_sections = {"pipeline", "estimator", "training", "simulator", "output"}
    return any(section in config for section in nested_sections)


def get_parameter_sampler_index_offset(config: dict) -> int | None:
    """Read the explicit theta-index offset, or None when the config sets none.

    Every theta index is used directly as the seed of the parameter RNG, so two
    runs that consume the same indices draw the same parameter sets. The offset
    is the first index a `TrainingDataGenerator` consumes; its semantics:

    - Absent (or None): the generator draws a base from OS entropy once per
      instance and records the value it used under this same key in the
      `generator_config` it writes into every output file. Independently
      launched runs -- one SLURM array task per file, all reading one YAML --
      therefore cover different theta blocks with no orchestration, and any file
      can be regenerated by passing its recorded value back explicitly.
    - Explicit: used as given. Repeated `generate_data_training()` calls on one
      generator (`ssms generate --n-files N`) advance from it by
      `n_parameter_sets` per file, so a caller deriving it from a SLURM array
      task id must use `task_id * n_files * n_parameter_sets`; the formula
      without `n_files` collides as soon as a task writes a second file.

    A YAML `PIPELINE.PARAMETER_SAMPLER_INDEX_OFFSET` reaches the generator as
    `config["pipeline"]["parameter_sampler_index_offset"]`: the CLI forwards the
    whole PIPELINE section (ssms/cli/generate.py), and a root-level YAML key is
    dropped entirely. The root lookup is kept as a fallback for programmatic
    callers that build the config by hand.

    Args:
        config: Generator configuration dictionary

    Returns:
        The explicit offset, or None when the config does not set one

    Raises:
        ValueError: If the offset is negative (an RNG seed cannot be)
    """
    offset = get_nested_config(
        config,
        "pipeline",
        "parameter_sampler_index_offset",
        default=config.get("parameter_sampler_index_offset"),
    )
    if offset is None:
        return None
    offset = int(offset)
    if offset < 0:
        raise ValueError(
            f"parameter_sampler_index_offset must be >= 0, got {offset}: theta "
            "indices seed the parameter RNG."
        )
    return offset
